# useless variable to illustrate TOML usage
title = 'Meeko TOML Configuration'

[agent]
name = 'Meeko'
[agent.recon]
duration = 15
channels = []
hopTime = 250
[agent.targeting]
scope = 5
targetWeights = [3,2,2,1,1]

[memory]
reconFile = 'memory/reconFile'
attackFile = 'memory/attackFile'
knownFile = '/path/to/file'

[environment]
server = 'http://127.0.0.1:8081'
auth = ['user','pass']
url = 'api/session'
